### PR TITLE
Add bq-jdbc-hikaricp-instrumented module 

### PR DESCRIPTION
**Pull request by elena-bondareva**
Ref: #69

### CODE REVIEW

**Comment by andrus** [comment]
```java
Set<Class<? extends ManagedDataSourceFactory>> collapsedSet = new HashSet<>(set);
for (Class<? extends ManagedDataSourceFactory> factory : set) {
    if (factory.getSuperclass() != Object.class) {
        collapsedSet.remove(factory.getSuperclass());
    }
}
```

In the code above we are either implicitly relying on a certain order of classes in a set, or are ignoring a possibility of multiple levels of inheritance (A extends B extends C extends Object)

**Comment by andrus** [comment]
(deleted my earlier comment; at a closer look `collapseSet` method looks correct.

**Comment by andrus** [comment]
A few notes...

## Mutable injectable object

```java
private void addHealthChecks(Injector injector, HikariDataSource ds) {
    HikariCPHealthCheckGroup group = injector.getInstance(HikariCPHealthCheckGroup.class);

    if (health != null) {
        group.getHealthChecks().putAll(health.createHealthChecksMap(injector, ds.getHikariPoolMXBean(), ds.getPoolName()));
    }
}
```
The code above from `HikariCPInstrumentedDataSourceFactory` mutates an injectable object (`HikariCPHealthCheckGroup`). This may potentially result in another user of `HikariCPHealthCheckGroup` to read the incomplete (empty) map of health checks , depending on initialization order. 

There's no easy way to invert this dependency. But perhaps we can take a modified approach from `DataSourceHealthCheckGroup`. E.g. make `Map<String, ManagedDataSourceFactory>` injectable, then use it to filter the Hikari data sources out of all data sources, and then create a healthcheck that would resolve the DataSource from the `DataSourceManager` on every check, and then read its parameters.

## Health check naming convention

This hasn't been formalized (and there were some changes recently), but we are trying to follow a certain naming convention for built-in health checks (e.g. `bq.jdbc.myDs.canConnect`). Hikari checks are using different naming (e.g. `myDs.pool.ConnectivityCheck`). Let's try to align it with the the emerging convention.

**Comment by ebondareva** [comment]
For instrumenting bq-hikaricp, [Dropwizard HealthChecks](https://github.com/brettwooldridge/HikariCP/wiki/Dropwizard-HealthChecks) and [Dropwizard Metrics](https://github.com/brettwooldridge/HikariCP/wiki/Dropwizard-Metrics) supported by HikariCP 2.2.0+ have been  integrated into the new module **bq-hikaricp-instrumented**.

ConnectivityCheck and Connection99Percent will be configured as follows:
```yaml
jdbc:
  derby2:
    type: "hikari-instrumented"
    poolName: "test2"
    minimumIdle: 1
    maximumPoolSize: 10
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    jdbcUrl: jdbc:derby:target/derby/derby2;create=true
    health:
      connectivityCheckTimeout: 250
      expected99thPercentile: 10
```
New node `health` has made us extend `HikariCPManagedDataSourceFactory`. Generally speaking, the complexity of a data source factories hierarchy can be arbitrary, so that a module can have several bq-jdbc implementations at the same time. Without property `type`set in YAML an exception is thrown as expected ([doc](https://github.com/bootique/bootique-jdbc/issues/62)). To cover such use cases, let's improve auto-detection of an available CP:
>**cp1<-extend cp1'<-extend cp1''** plugged in -> configs without 'type' are to be mapped on **the cp1'' type - the last child in linear hierarchy**, the others - on the set 'type'. **In case of nonlinear hierarchy - throw an exception.**

The issue #72 for this has been created.

**Comment by ebondareva** [comment]
In response to Andrus's notes, some improvements done e8a2a16:
* follow naming convention for built-in health checks
* make Map<String, ManagedDataSourceFactory> injectable

**Pull request merged**
